name: template-validator
on: 
  push:
    paths:
      - 'template.yaml'

jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS SAM CLI
      - name: Install AWS SAM CLI
        run: |
            sudo apt-get update
            sudo apt-get install -y unzip curl
            curl -Lo sam-cli.zip https://github.com/aws/aws-sam-cli/releases/download/v2.0.0/aws-sam-cli-linux-x86_64.zip
            unzip sam-cli.zip -d /home/ubuntu/
            sudo /home/ubuntu/aws-sam-cli-linux-x86_64/install
            sam --version


      # Step 3: Validate the SAM template
      - name: Validate SAM template
        run: sam validate
